PasswordAuthentication no
KbdInteractiveAuthentication no
PermitEmptyPasswords no
PermitRootLogin no
PubkeyAuthentication yes
AllowGroups ssh-admins
AllowAgentForwarding no
AllowTcpForwarding local
GatewayPorts no
X11Forwarding no
MaxAuthTries 3
LogLevel VERBOSE
